### ISSUE TITLE
Enable table stage feature of snowflake (allowing non-native s3 account)

### ISSUE THREAD

**Issue by qmnonic** [transferwise/pipelinewise-target-snowflake#22]
Current pipeline code needs a native (aws) s3 account, which i don't have.  So i've updated the code to allow table staging (a feature of snowflake) that doesn't need an s3 link to upload data for a table.

I also added the ability to configure alternative s3 endpoints (i use digitalocean).

**Comment by andyoneal** [comment]
Does this have any impact on speed? I would guess a single transfer is better than two.

**Comment by qmnonic** [comment]
Don't have a measured impact on speed, but would agree that a single transfer is likely better than two, assuming snowflakes internal stage's are local.

**Comment by qmnonic** [comment]
Enabling this feature seems like a quick win, why not do it?  Snowflake seems to recommend using internal stages for data loading anyways, and it simplifies the flow (not requiring an s3 account).

My PR does most of the work, i just lost track of it.  Happy to have someone on the transferwise side take it on.

**Comment by koszti** [comment]
hey @qmnonic , we're about to improve s3 connection by adding profile based authentication and environment variables so we don't need to have hard coded aws credentials in `config.json`. I think this is a good time to take a look onto your PR and do this together.

I agree, using internal stages and the snowflake `PUT` object is a quick win to support non-AWS storages, including Azure and Google Cloud Storages so I think now we can make this feature request.

I have one question:
Currently you use  `if not 'aws_access_key_id' in self.connection_config:` condition to detect if we want to use internal storage. This condition will not work if we will add very soon AWS profile based authentication, because that won't require secret keys. 

Do you have any idea how we can decide elegantly if we want to use internal or external stages in `config.json`?
Should we add something like `use_external_name_stages` to `config.json` that defaults to `false` to keep backward compatibility with with existing configs on live systems? Do you have any better more elegant idea?

What do you think?

**Comment by qmnonic** [comment]
ignoring my PR, i think you should use internal stages if the s3/external stage isn't configured.  Meaning, you shouldn't have to configure anything to use an internal stage - it would default to using the target tables own stage.  This target appears to take that approach - https://github.com/datamill-co/target-snowflake

**Comment by koszti** [comment]
I think you're right and internal stages should be used by default. I added `s3_endpoint_url` as part of https://github.com/transferwise/pipelinewise-target-snowflake/pull/93 for now. to use it with non-native aws s3 sccounts.

Support for internal stages may arrive soon as well. 🤞
