### ISSUE TITLE
schema name in target table?

### ISSUE THREAD

**Issue by SteveDMurphy** [transferwise/pipelinewise-target-snowflake#220]
Is it possible to include the schema name in the target table in case of common table names from different schemas? I have been looking around through any of the optional flags in the repo and docs but have been unable to find support for this - my apologies in advance if it is already answered somewhere!

**Comment by Samira-El** [comment]
Hey @SteveDMurphy,

I'm afraid I'm not following you here, care to share a simple example of this case and config?
It sounds tho that the `schema_mapping` config might be usefull, have you taken a look at it?

**Comment by SteveDMurphy** [comment]
Hi @Samira-El ! My apologies for not seeing this :( 

As an example, say I have an integration that loads all production data into `raw.production`

Currently when loading a stream (example `dbo-Users`), the end result looks something like `raw.production.users` - I was hoping to be able to have the end result look more like `raw.production.dbo_users`

Looking at the schema mapping, it appears to handle loading to multiple schemas whereas I was just trying to avoid issues in case somebody ever creates a table with the same name in a separate schema (i.e. stream_id `rpt-Users`)

Thanks again for your help/response and my apologies about the lack of reply!

**Comment by Samira-El** [comment]
I'm afraid it's not possible to include the schema name in the table name, it doesn't align with the Singer specification.

I think the schema mapping could still be useful to protect against the scenario you described, since you can map the different source schemas to different schemas in target, so you could map the source schema `dbo` to target schema `raw.production` and if someone were to create a table `users` under some schema `new-schema` then map that to, say, `raw.production_new_schema`.

On a side note, you might wanna name the target schema the same as source schema, that way you know in which schema goes which table, and people familiar with the structure in the source would have no problem navigating the target.

**Comment by SteveDMurphy** [comment]
Thanks for the info and alternative @Samira-El ! We were hoping to replicate the same setup we have with Stitch today, where the schema is included in the created target table name (saw this using the data-mill version as well). I didn't realize that it was sort of an anti-pattern to the singer spec to do that. The workaround you mentioned makes sense, especially when considering users familiar with the source structure - thanks for the suggestion!
