### ISSUE TITLE
Snowflake not loading any rows

### ISSUE THREAD

**Issue by amigold** [transferwise/pipelinewise-target-snowflake#97]
Hi,
Following the MySQL to Snowflake tutorial, for some reason Snowflake does not load any rows successfully, but pipelinewise still shows a success

Here are the logs:
```
time=2020-09-03 17:36:07 logger_name=pipelinewise.fastsync.commons.tap_mysql log_level=INFO message=Running query: SHOW KEYS FROM `db`.`amitest` WHERE Key_name = 'PRIMARY'
time=2020-09-03 17:36:08 logger_name=pipelinewise.fastsync.commons.target_snowflake log_level=INFO message=Uploading to S3 bucket: SOMEBUCKET, local file: /root/.pipelinewise/tmp/pipelinewise_fastsync_db.amitest_20200903-173604.csv.gz, S3 key: snowflake-imports/pipelinewise_db.amitest_20200903-173608.csv.gz
time=2020-09-03 17:36:13 logger_name=pipelinewise.fastsync.commons.target_snowflake log_level=INFO message=Loading snowflake-imports/pipelinewise_dbamitest_20200903-173608.csv.gz into Snowflake...
time=2020-09-03 17:36:15 logger_name=pipelinewise.fastsync.commons.target_snowflake log_level=INFO message=Loading into INCOMING_MYSQL."AMITEST_TEMP": **{"inserts": 0, "updates": 0, "size_bytes": 137}**
time=2020-09-03 17:36:15 logger_name=pipelinewise.fastsync.commons.target_snowflake log_level=INFO message=Deleting snowflake-imports/pipelinewise_db.amitest_20200903-173608.csv.gz from S3...
time=2020-09-03 17:36:15 logger_name=pipelinewise.fastsync.commons.target_snowflake log_level=INFO message=Applying obfuscation rules
time=2020-09-03 17:36:18 logger_name=pipelinewise.fastsync.commons.utils log_level=INFO message=Saving new state file to /root/.pipelinewise/snowflake/somewhere/state.json
time=2020-09-03 17:36:22 logger_name=pipelinewise.fastsync.mysql_to_snowflake log_level=INFO message=
```

1. I created a test table to sync
2. If we look at the gzipped file we can see it has 4 rows which are exported successfully.
[pipelinewise_db.amitest_20200903-134750.csv.gz](https://github.com/transferwise/pipelinewise-target-snowflake/files/5170383/pipelinewise_db.amitest_20200903-134750.csv.gz)

I have no idea why no rows are actually inserted into Snowflake

**Comment by pbegle** [comment]
I'm running into the exact same issue. The tables and fields actually get imported successfully but i have 0 data.

**Comment by pbegle** [comment]
I figured out the issue I was having. I had created an external snowflake stage `MY_STAGE` with the s3 URL that was something like this: `s3://my-bucket/my-s3-prefix`. I was also including the `my-s3-prefix` in the snowflake target YAML config file. When the target runs, it creates a `COPY INTO` statement that tries to copy from `'@MY_STAGE/my-s3-prefix/my-data.csv'`. However, that path is incorrect as `@MY_STAGE` is an alias for the value provided in the s3 URL which in my case I defined as `s3://my-bucket/my-s3-prefix`. So the `COPY INTO` statement is trying to copy from `s3://my-bucket/my-s3-prefix/my-s3-prefix/my-data.csv`which of course doesn't exist. But instead of throwing an error, Snowflake will report success with a "0 files processed" message. The fix in my case was simple: just create the stage with the bucket name only and don't include the `my-s3-prefix` in the URL. So it should just look like this: `s3://my-bucket`. That way it will properly construct the correct path to your CSV files.
